language: java
install: true

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - chmod +x gradlew

stages:
  - name: build

jobs:
  include:
    - stage: build
      script: ./gradlew build
