language: java
install: true

sudo: false
addons:
	apt:
		packages:
			- oracle-java8-installer

before_install:
	- chmod +x gradlew

stages:
	- name: build
	- name: release
	  if: branch = release

jobs:
	include:
		- stage: build
		  script: ./gradlew build
		- stage: release
		  script: ./gradlew bintrayUpload -x test -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER
